### PR TITLE
only consider pods that have been scheduled

### LINKED ISSUE #77: Incorrect resource accounting for pods that are scheduled (allocated resources) but not Running
Here is an example (trimmed down slightly) of a pod that is not counted by kubectl-view-allocations but it is counted by the kube-scheduler as consuming nvidia.com/gpu resources (and other resources).

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-19T19:01:59Z"
  name: test
  namespace: data-ingest
spec:
  containers:
  - command:
    - sh
    - -exc
    - echo hello
    image: busybox:does-not-exist
    imagePullPolicy: Always
    name: msr
    resources:
      limits:
        cpu: "128"
        memory: 256Gi
        nvidia.com/gpu: "16"
      requests:
        cpu: "1"
        memory: 256Mi
        nvidia.com/gpu: "16"
  initContainers:
  - command:
    - sh
    - -exc
    - echo hello init
    image: minio/mc
    imagePullPolicy: Always
    name: get-input-data
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 256m
        memory: 256Mi
  nodeName: dgx-1
  priority: 100
  priorityClassName: free
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-10-23T20:29:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-10-23T20:29:02Z"
    message: 'containers with unready status: [msr]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-10-23T20:29:02Z"
    message: 'containers with unready status: [msr]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-10-23T20:29:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: busybox:does-not-exist
    imageID: ""
    lastState: {}
    name: msr
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "busybox:does-not-exist"
        reason: ImagePullBackOff
  hostIP: 10.1.4.5
  initContainerStatuses:
  - containerID: docker://cc4cc2745ae7a23d0f06d4879fab1b6207b301b44379186db0d172ded1af5956
    image: minio/mc:latest
    imageID: docker-pullable://minio/mc@sha256:ac82bb6219b60b662e28c6f0d642f36bbf7803fc74929c11319f4592203fa752
    lastState: {}
    name: get-input-data
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://cc4cc2745ae7a23d0f06d4879fab1b6207b301b44379186db0d172ded1af5956
        exitCode: 0
        finishedAt: "2020-10-23T20:29:18Z"
        reason: Completed
        startedAt: "2020-10-23T20:29:04Z"
  phase: Pending
  podIP: 10.42.15.92
  podIPs:
  - ip: 10.42.15.92
  qosClass: Burstable
  startTime: "2020-10-23T20:29:02Z"
```

It looks like the issue might be with this line 
```rust
.and_then(|ps| ps.node_name.as_ref().map(|s| s == "Running"))
```
in src/main.rs:183

Also it looks like you look for running containers right after that.  In my case the containers are not running (yet).

You only consider pods that have a phase of Running.  It you want kubectl-view-allocations to provide truely what resoruces are available on a node with `kubectl-view-allocations -g node -g resource` then we need to consider more then just running pods but Pending as well.  

The condition we might want is that nodeName is set or that there is an entry in the status.conditions array that has type PodScheduled and status "True".

This can be recreated by applying this (just need a bad image name):
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kyle-test
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: main
        image: nvidia/cuda:does-not-exist
        args: ['sleep', 'infinity']
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
            nvidia.com/gpu: 1
      restartPolicy: Never
```

### PR DESCRIPTION
**Pull request by ktarplee**
Only consider pods that have been scheduled independent of if they are running or not.  They still consume resources from the scheudler's perspective.

Closes #77

### CODE REVIEW

**Comment by ktarplee** [comment]
I think we should not use "nominatedNodeName" because this is not actually the node that this pod is scheduled to.  It is the one that the scheduler just preempted a pod on to make room, but the scheduler might put the pod on a different node.  I do not believe it is scheduled at the time that nominatedNodeName is set.

File: src/main.rs [hunk 1]
```diff
@@ -177,25 +186,11 @@ async fn collect_from_pods(
...
-            .or_else(|| spec.and_then(|m| m.node_name.clone()));
+        let node_name = spec.and_then(|m| m.node_name.clone());
         let containers = spec.map(|s| s.containers.clone()).unwrap_or_else(|| vec![]);
-        for (_, container) in containers.into_iter().enumerate().filter(|(i, _)| {
-            status
-                .and_then(|s| s.container_statuses.as_ref())
-                .and_then(|v| v.get(*i).and_then(|v| v.state.as_ref()))
-                .map(|s| s.running.is_some())
-                .unwrap_or(true)
-        }) {
```
Comment (davidB) [inline src/main.rs:198]: This filter is to avoid to count resources (CPU, memory,...) used by non-running container like thoses used for init phase.

**Comment by davidB** [comment]
I agree to the fact to count scheduled if it's "planned/reserved" + running but IMHO, the count should not include resources used by a stopped container.

**Comment by ktarplee** [comment]
Let me see if I can figure out how the kube-scheduler handles resources of a stopped container.  If it frees up the resources then what you said makes sense to me.  If the scheduler still considers those resources allocated then I think the tool should consider them allocated to the node as well.   Otherwise someone will look at the output of this tool and say wait, it says I have 2 free GPUs on that node but I cannot use then (schedule a pod that uses 2 GPU on that node).

I did a test by creating a pod with two containers (`sleep infinity` and `sleep 120`) that consumed all of one type of resource (2+6 GPUs).  It was scheduled fine.  I then created another pod asking for 1 GPU.  That second pod never go scheduled because I only have 8 GPUs in that cluster.  So the scheduler considers the resources allocated even when the containers have completed running or have not even started running.

Specifically kube-scheduler uses this code to determine the number of resources for a pod

```go
func computePodResourceRequest(pod *v1.Pod) *preFilterState {
	result := &preFilterState{}
	for _, container := range pod.Spec.Containers {
		result.Add(container.Resources.Requests)
	}

	// take max_resource(sum_pod, any_init_container)
	for _, container := range pod.Spec.InitContainers {
		result.SetMaxResource(container.Resources.Requests)
	}

	// If Overhead is being utilized, add to the total requests for the pod
	if pod.Spec.Overhead != nil && utilfeature.DefaultFeatureGate.Enabled(features.PodOverhead) {
		result.Add(pod.Spec.Overhead)
	}

	return result
}
```

Notice they account for overhead and initContainers.  See the [docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) for more details and rationale.  I can try to add that to kubectl-view-allocations if you want?

**Comment by davidB** [comment]
My concern was about init container. In first version I count them as allocated resources but iirc I noticed difference between the full count the node's allocation.

I agree about the approach to compute scheduled like in the scheduler, mainly to answer "can I schedule my pod ?". 

Thanks for the investigation and the clarification, and the PR.

**Comment by davidB** [comment]
Yes, please, can you include into the PR the same formula (with the link you provide, as doc) of the "Pod’s effective request/limit".

I'll do a release after the merge of the PR (at least the WE after).

File: src/main.rs (hunk 1 above)
Comment (ktarplee) [reply src/main.rs:198]: The "containers" field that is being filtered is only the regular containers.  It does not include the initContainers.  Also the initContainer status information is not there.  It is in initContainerStatuses.  See the associated issue for an example.

Comment (ktarplee) [reply src/main.rs:198]: I think this is resolved based on your latest comment but correct me if I am wrong.

File: src/main.rs [hunk 2]
```diff
@@ -205,45 +231,26 @@ async fn collect_from_pods(
...
-                            )
-                        })?;
-                        resources.push(Resource {
-                            kind: request.0,
-                            usage: ResourceUsage::Requested,
-                            quantity,
-                            location: location.clone(),
-                        });
-                    }
+                    // TODO do max resource for this pod
```
Comment (ktarplee) [inline src/main.rs:234]: @davidB How do you want to account for the initContainers.  In logic elsewhere you assume that the pod resources all add.  initContainers break that assumption.  One simple solution is to only add one entry to `resource_names` for each pod.  This would make the container_name field obsolete.  Does that work for you or do you really want to track this at the container level and not the pod level?

File: Cargo.toml [hunk 3]
```diff
@@ -14,7 +14,7 @@ exclude = ["/.github", "/.dependabot", ".gitignore"]
 [dependencies]
 tokio = { version = "0.2.22", features = ["full"]}
 kube = "0.43.0"
-k8s-openapi = { version = "0.9.0", features = ["v1_15"], default-features = false }
+k8s-openapi = { version = "0.9.0", features = ["v1_16"], default-features = false }
```
Comment (davidB) [inline Cargo.toml:17]: does upgrade to v1_16 required ?

File: src/main.rs (hunk 2 above)
Comment (davidB) [reply src/main.rs:234]: I'm in favor to remove the container level. it should ease to mimic the sheduler computation and I guess nobody display/use the container level info.

File: Cargo.toml (hunk 3 above)
Comment (ktarplee) [reply Cargo.toml:17]: It is required for sepc.overhead to be defined.

File: src/main.rs (hunk 2 above)
Comment (ktarplee) [reply src/main.rs]: I implemented this.

**Comment by davidB** [comment]
Thanks, I quickly review it, you made some nice refactor. I'll take more time to re-read it, play with it and add a change in the display, before make a release as 0.9.x.
